### ISSUE TITLE
Client

### ISSUE THREAD

**Issue by LaisFranco** [BeerOnline/BeerOnline#3]
That is  part of client, here is where the client makes your buys
- [x] ![cadastre-se para poder finalizar a compra](https://cloud.githubusercontent.com/assets/10939505/10126481/ebaf5b4e-6569-11e5-8c3c-7fa7f9b56225.png)
- [ ] ![carrinho de comprar fechar pedido](https://cloud.githubusercontent.com/assets/10939505/10126482/ebd5130c-6569-11e5-90d3-efb40a3a7a38.png)
- [ ]  ![carrinho de comprar minha geladeira](https://cloud.githubusercontent.com/assets/10939505/10126484/ec0e8272-6569-11e5-8174-5e7ca8f158d9.png)
- [ ]  ![carrinho de compras finalizar pedido](https://cloud.githubusercontent.com/assets/10939505/10126483/ebf8adf8-6569-11e5-8826-2e77865952b5.png)
- [ ] ![tela inicial](https://cloud.githubusercontent.com/assets/10939505/10126485/ec290b06-6569-11e5-8412-8b6ef2172b41.png)

 buys.

**Comment by MarceloBorgesP** [comment]
No time enough to do this
